# Generated by Django 5.0.8 on 2024-10-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='Дата создания')),
                ('latest_update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('description_ru', models.TextField(default='', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(default='', null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(default='', null=True, verbose_name='Описание')),
                ('main_photo', models.ImageField(upload_to='NewsMainImage/%Y/%m/%d/', verbose_name='Главное фото новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='news_images/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_ru', models.ImageField(null=True, upload_to='news_images/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_en', models.ImageField(null=True, upload_to='news_images/%Y/%m/%d/', verbose_name='Фото')),
                ('photo_ky', models.ImageField(null=True, upload_to='news_images/%Y/%m/%d/', verbose_name='Фото')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='News.news', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Фото новостей',
                'verbose_name_plural': 'Фото новостей',
            },
        ),
    ]
