# Generated by Django 5.0.8 on 2024-08-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='news/main_photos/', verbose_name='Фото основной')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='News', to='News.news', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Фото новостей',
                'verbose_name_plural': 'Фото новостей',
            },
        ),
    ]
