# Generated by Django 5.0.8 on 2024-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='address_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='news',
            name='address_ky',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='news',
            name='address_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
