# Generated by Django 5.0.8 on 2024-08-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Контактный номер')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('certificate_duration', models.CharField(max_length=50, verbose_name='Срок сертификата')),
            ],
            options={
                'verbose_name': 'Наблюдатели',
                'verbose_name_plural': 'Наблюдатель',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='service-images/', verbose_name='Фото какого-то сервиса')),
                ('service', models.CharField(max_length=64, unique=True, verbose_name='Тип обслуживания')),
            ],
            options={
                'verbose_name': 'Сервисы',
                'verbose_name_plural': 'Сервис',
            },
        ),
        migrations.CreateModel(
            name='CertifiedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(auto_created=True, verbose_name='Дата окончания')),
                ('issue_date', models.DateField(auto_created=True, verbose_name='День получения')),
                ('company_email', models.EmailField(max_length=254)),
                ('certificate_name', models.CharField(max_length=28)),
                ('company_photo', models.ImageField(upload_to='company_photos/', verbose_name='Фото компании (внутри или снаружи)')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('trademark', models.CharField(max_length=255, verbose_name='Товарный знак')),
                ('registration_number', models.CharField(max_length=100, verbose_name='Регистрационный номер')),
                ('region', models.CharField(max_length=255, verbose_name='Область')),
                ('company_address', models.TextField(verbose_name='Адрес компании')),
                ('certificate_photo', models.ImageField(upload_to='certificate_photos/', verbose_name='Фото сертификата')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код')),
                ('certificate_type', models.CharField(choices=[('Сертифицированный', 'Сертифицированный'), ('В процессе', 'В процессе'), ('Приостоновлено', 'Приостоновлено'), ('Истекшие', 'Истекшие')], default='В процессе', max_length=50, verbose_name='Тип сертификата')),
                ('observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Certification.observer', verbose_name='Наблюдатель')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='Certification.service', verbose_name='Тип обслуживания')),
            ],
            options={
                'verbose_name': 'Сертифицированные компании',
                'verbose_name_plural': 'Сертифицированная компания',
            },
        ),
    ]
