# Generated by Django 5.0.8 on 2024-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifiedcompany',
            name='certificate_name_en',
            field=models.CharField(max_length=28, null=True, verbose_name='Название сертификата'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='certificate_name_ky',
            field=models.CharField(max_length=28, null=True, verbose_name='Название сертификата'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='certificate_name_ru',
            field=models.CharField(max_length=28, null=True, verbose_name='Название сертификата'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='certificate_type_en',
            field=models.CharField(choices=[('Сертифицированный', 'Сертифицированный'), ('В процессе', 'В процессе'), ('Приостановлено', 'Приостановлено'), ('Истекший', 'Истекший')], default='В процессе', max_length=50, null=True, verbose_name='Тип сертификата'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='certificate_type_ky',
            field=models.CharField(choices=[('Сертифицированный', 'Сертифицированный'), ('В процессе', 'В процессе'), ('Приостановлено', 'Приостановлено'), ('Истекший', 'Истекший')], default='В процессе', max_length=50, null=True, verbose_name='Тип сертификата'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='certificate_type_ru',
            field=models.CharField(choices=[('Сертифицированный', 'Сертифицированный'), ('В процессе', 'В процессе'), ('Приостановлено', 'Приостановлено'), ('Истекший', 'Истекший')], default='В процессе', max_length=50, null=True, verbose_name='Тип сертификата'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='company_address_en',
            field=models.TextField(null=True, unique=True, verbose_name='Адрес компании'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='company_address_ky',
            field=models.TextField(null=True, unique=True, verbose_name='Адрес компании'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='company_address_ru',
            field=models.TextField(null=True, unique=True, verbose_name='Адрес компании'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='company_name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='company_name_ky',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='company_name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='region_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='region_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='region_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='trademark_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Товарный знак'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='trademark_ky',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Товарный знак'),
        ),
        migrations.AddField(
            model_name='certifiedcompany',
            name='trademark_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Товарный знак'),
        ),
        migrations.AddField(
            model_name='observer',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='observer',
            name='address_ky',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='observer',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='observer',
            name='contact_number_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Контактный номер'),
        ),
        migrations.AddField(
            model_name='observer',
            name='contact_number_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='Контактный номер'),
        ),
        migrations.AddField(
            model_name='observer',
            name='contact_number_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Контактный номер'),
        ),
        migrations.AddField(
            model_name='observer',
            name='fullname_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AddField(
            model_name='observer',
            name='fullname_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AddField(
            model_name='observer',
            name='fullname_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ф.И.О'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_en',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Тип обслуживания'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_ky',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Тип обслуживания'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_ru',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Тип обслуживания'),
        ),
    ]
