# Generated by Django 5.0.8 on 2024-09-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifiedcompany',
            name='certificate_type',
            field=models.CharField(choices=[('Сертифицированный', 'Сертифицированный'), ('В процессе', 'В процессе'), ('Приостановлено', 'Приостановлено'), ('Истекший', 'Истекший')], max_length=50, verbose_name='Тип сертификата'),
        ),
    ]
