# Generated by Django 5.0.8 on 2024-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecode',
            name='code_name_en',
            field=models.TextField(null=True, verbose_name='Название кода'),
        ),
        migrations.AddField(
            model_name='ecode',
            name='code_name_ky',
            field=models.TextField(null=True, verbose_name='Название кода'),
        ),
        migrations.AddField(
            model_name='ecode',
            name='code_name_ru',
            field=models.TextField(null=True, verbose_name='Название кода'),
        ),
        migrations.AddField(
            model_name='ecode',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ecode',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='ecode',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
