# Generated by Django 5.0.8 on 2024-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='BlackListCompany/')),
            ],
        ),
    ]
