# Generated by Django 5.0.8 on 2024-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='icon',
        ),
        migrations.AddField(
            model_name='ourteam',
            name='social_network_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на соц. сеть'),
        ),
    ]
