# Generated by Django 5.0.8 on 2024-09-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_blacklistcompanies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='icon',
        ),
    ]
