# Generated by Django 5.0.8 on 2024-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0003_remove_boycott_company_logo_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourachievementcertificateimage',
            options={'verbose_name': 'Наш сертификат', 'verbose_name_plural': 'Наши сертификаты'},
        ),
        migrations.AddField(
            model_name='client',
            name='url_en',
            field=models.URLField(null=True, verbose_name='Ссылка на клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='url_ky',
            field=models.URLField(null=True, verbose_name='Ссылка на клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='url_ru',
            field=models.URLField(null=True, verbose_name='Ссылка на клиента'),
        ),
        migrations.AddField(
            model_name='mainphonenumber',
            name='number_en',
            field=models.CharField(max_length=9, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='mainphonenumber',
            name='number_ky',
            field=models.CharField(max_length=9, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='mainphonenumber',
            name='number_ru',
            field=models.CharField(max_length=9, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='mobileappurl',
            name='app_store_en',
            field=models.URLField(null=True, verbose_name='AppStoreUrl'),
        ),
        migrations.AddField(
            model_name='mobileappurl',
            name='app_store_ky',
            field=models.URLField(null=True, verbose_name='AppStoreUrl'),
        ),
        migrations.AddField(
            model_name='mobileappurl',
            name='app_store_ru',
            field=models.URLField(null=True, verbose_name='AppStoreUrl'),
        ),
        migrations.AddField(
            model_name='mobileappurl',
            name='google_play_en',
            field=models.URLField(null=True, verbose_name='GooglePlayUrl'),
        ),
        migrations.AddField(
            model_name='mobileappurl',
            name='google_play_ky',
            field=models.URLField(null=True, verbose_name='GooglePlayUrl'),
        ),
        migrations.AddField(
            model_name='mobileappurl',
            name='google_play_ru',
            field=models.URLField(null=True, verbose_name='GooglePlayUrl'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='number_of_domestic_enterprises_en',
            field=models.TextField(null=True, verbose_name='Количество отечественных предприятий'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='number_of_domestic_enterprises_ky',
            field=models.TextField(null=True, verbose_name='Количество отечественных предприятий'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='number_of_domestic_enterprises_ru',
            field=models.TextField(null=True, verbose_name='Количество отечественных предприятий'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='number_of_professionals_en',
            field=models.TextField(null=True, verbose_name='Количество профессионалов'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='number_of_professionals_ky',
            field=models.TextField(null=True, verbose_name='Количество профессионалов'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='number_of_professionals_ru',
            field=models.TextField(null=True, verbose_name='Количество профессионалов'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='number_offoreign_enterprises_en',
            field=models.TextField(null=True, verbose_name='Количество иностранных предприятий'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='number_offoreign_enterprises_ky',
            field=models.TextField(null=True, verbose_name='Количество иностранных предприятий'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='number_offoreign_enterprises_ru',
            field=models.TextField(null=True, verbose_name='Количество иностранных предприятий'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='year_of_foundation_en',
            field=models.TextField(null=True, verbose_name='Год основания'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='year_of_foundation_ky',
            field=models.TextField(null=True, verbose_name='Год основания'),
        ),
        migrations.AddField(
            model_name='ourindicators',
            name='year_of_foundation_ru',
            field=models.TextField(null=True, verbose_name='Год основания'),
        ),
        migrations.AddField(
            model_name='partner',
            name='url_en',
            field=models.URLField(null=True, verbose_name='Ссылка на партнера'),
        ),
        migrations.AddField(
            model_name='partner',
            name='url_ky',
            field=models.URLField(null=True, verbose_name='Ссылка на партнера'),
        ),
        migrations.AddField(
            model_name='partner',
            name='url_ru',
            field=models.URLField(null=True, verbose_name='Ссылка на партнера'),
        ),
        migrations.AddField(
            model_name='ratingandhowyouheardaboutoursite',
            name='social_network_en',
            field=models.CharField(max_length=9, null=True, verbose_name='Социальная сеть'),
        ),
        migrations.AddField(
            model_name='ratingandhowyouheardaboutoursite',
            name='social_network_ky',
            field=models.CharField(max_length=9, null=True, verbose_name='Социальная сеть'),
        ),
        migrations.AddField(
            model_name='ratingandhowyouheardaboutoursite',
            name='social_network_ru',
            field=models.CharField(max_length=9, null=True, verbose_name='Социальная сеть'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='url_en',
            field=models.TextField(null=True, verbose_name='Ссылка на социальную сеть'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='url_ky',
            field=models.TextField(null=True, verbose_name='Ссылка на социальную сеть'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='url_ru',
            field=models.TextField(null=True, verbose_name='Ссылка на социальную сеть'),
        ),
        migrations.AddField(
            model_name='suggestionsorcomplaints',
            name='telegram_url_en',
            field=models.URLField(null=True, verbose_name='URL для жалоб и предложений Telegram'),
        ),
        migrations.AddField(
            model_name='suggestionsorcomplaints',
            name='telegram_url_ky',
            field=models.URLField(null=True, verbose_name='URL для жалоб и предложений Telegram'),
        ),
        migrations.AddField(
            model_name='suggestionsorcomplaints',
            name='telegram_url_ru',
            field=models.URLField(null=True, verbose_name='URL для жалоб и предложений Telegram'),
        ),
        migrations.AddField(
            model_name='suggestionsorcomplaints',
            name='whatsapp_url_en',
            field=models.URLField(null=True, verbose_name='URL для жалоб и предложений WhatsApp'),
        ),
        migrations.AddField(
            model_name='suggestionsorcomplaints',
            name='whatsapp_url_ky',
            field=models.URLField(null=True, verbose_name='URL для жалоб и предложений WhatsApp'),
        ),
        migrations.AddField(
            model_name='suggestionsorcomplaints',
            name='whatsapp_url_ru',
            field=models.URLField(null=True, verbose_name='URL для жалоб и предложений WhatsApp'),
        ),
    ]
