# Generated by Django 5.0.8 on 2024-08-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBarCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13)),
                ('bar_type', models.CharField(choices=[('EAN_13', 'EAN_13'), ('UPC-A', 'UPC-A'), ('EAN-8', 'EAN-8'), ('UPC-E', 'UPC-E')], max_length=6)),
                ('product_status', models.CharField(max_length=42)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certification.certifiedcompany')),
            ],
        ),
    ]
