# Generated by Django 5.1.1 on 2024-09-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBarCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=14, unique=True, verbose_name='Штрих код продукта')),
                ('product_name', models.CharField(verbose_name='Название продукта')),
                ('bar_type', models.CharField(choices=[('EAN_13', 'EAN_13'), ('UPC-A', 'UPC-A'), ('EAN-8', 'EAN-8'), ('UPC-E', 'UPC-E')], max_length=6, verbose_name='Тип кода продукта')),
                ('product_status', models.CharField(choices=[('Проверенный', 'Проверенный'), ('Не проверенный', 'Не проверенный')], max_length=42, verbose_name='Статус продукта Проверенный/Не проверенный')),
                ('adal_center_icon', models.ImageField(upload_to='AdalCenterIcon/', verbose_name='Иконка сертифицированной компании Adal Center')),
                ('product_image', models.ImageField(upload_to='BarCodeProductImages/', verbose_name='Изображение продукта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certification.certifiedcompany', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Штрих-код',
                'verbose_name_plural': 'Штрих-коды',
            },
        ),
    ]
