# Generated by Django 5.0.8 on 2024-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarCode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbarcode',
            name='code_en',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='Штрих код продукта'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='code_ky',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='Штрих код продукта'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='code_ru',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='Штрих код продукта'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='product_name_en',
            field=models.TextField(null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='product_name_ky',
            field=models.TextField(null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='product_name_ru',
            field=models.TextField(null=True, verbose_name='Название продукта'),
        ),
    ]
