# Generated by Django 5.0.8 on 2024-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarCode', '0002_productbarcode_code_en_productbarcode_code_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbarcode',
            name='code_en',
        ),
        migrations.RemoveField(
            model_name='productbarcode',
            name='code_ky',
        ),
        migrations.RemoveField(
            model_name='productbarcode',
            name='code_ru',
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='bar_type_en',
            field=models.CharField(choices=[('EAN_13', 'EAN_13'), ('UPC-A', 'UPC-A'), ('EAN-8', 'EAN-8'), ('UPC-E', 'UPC-E')], max_length=6, null=True, verbose_name='Тип кода продукта'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='bar_type_ky',
            field=models.CharField(choices=[('EAN_13', 'EAN_13'), ('UPC-A', 'UPC-A'), ('EAN-8', 'EAN-8'), ('UPC-E', 'UPC-E')], max_length=6, null=True, verbose_name='Тип кода продукта'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='bar_type_ru',
            field=models.CharField(choices=[('EAN_13', 'EAN_13'), ('UPC-A', 'UPC-A'), ('EAN-8', 'EAN-8'), ('UPC-E', 'UPC-E')], max_length=6, null=True, verbose_name='Тип кода продукта'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='product_status_en',
            field=models.CharField(choices=[('Проверенный', 'Проверенный'), ('Не проверенный', 'Не проверенный')], max_length=42, null=True, verbose_name='Статус продукта Проверенный/Не проверенный'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='product_status_ky',
            field=models.CharField(choices=[('Проверенный', 'Проверенный'), ('Не проверенный', 'Не проверенный')], max_length=42, null=True, verbose_name='Статус продукта Проверенный/Не проверенный'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='product_status_ru',
            field=models.CharField(choices=[('Проверенный', 'Проверенный'), ('Не проверенный', 'Не проверенный')], max_length=42, null=True, verbose_name='Статус продукта Проверенный/Не проверенный'),
        ),
    ]
